#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_gcc-4.8_ius:${IUS_HOME}/tools/cdsgcc/gcc/4.8/install/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

irun -sv -uvm -quiet -access +rwc -timescale 1ns/1ns \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.svh \
    +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/mgc_axi4_v1_0_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/mgc_apb3_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/top_params_pkg.sv \
    top_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_master.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules/apb_slave.sv \
    /home/intern2/axi_2apb_bridge/axi2apb_bridge.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_top.sv \
    hvl_top.sv \
    -sv_root ${QUESTA_MVC_HOME}/questa_mvc_core/linux_gcc-4.8_ius \
    -sv_lib libapb3_IN_SystemVerilog_IUS_full \
    -sv_lib libaxi4_IN_SystemVerilog_IUS_full \
    +UVM_TESTNAME=top_test_base \
    +SEQ=top_example_vseq
