#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_gcc-4.8.3_vcs:${VCS_HOME}/gnu/linux/gcc-4.8.3/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

vcs -sverilog -ntb_opts uvm -debug_access+w -quiet  -timescale=1ns/1ns \
    -ld ${VCS_HOME}/gnu/linux/gcc-4.8.3/bin/g++ \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.svh \
    +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/mgc_axi4_v1_0_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/mgc_apb3_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/top_params_pkg.sv \
    top_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_master.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules/apb_slave.sv \
    /home/intern2/axi_2apb_bridge/axi2apb_bridge.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_top.sv \
    hvl_top.sv \
    -syslib ${QUESTA_MVC_HOME}/questa_mvc_core/linux_gcc-4.8.3_vcs/libapb3_IN_SystemVerilog_VCS_full.so \
    -syslib ${QUESTA_MVC_HOME}/questa_mvc_core/linux_gcc-4.8.3_vcs/libaxi4_IN_SystemVerilog_VCS_full.so

./simv +UVM_TESTNAME=top_test_base +SEQ=top_example_vseq
